### ISSUE TITLE
error on poke.io.js

### ISSUE THREAD

**Issue by mauscoelho** [BasouKazuma/pokemon-go-node-slack-notifier#1]
[i] Received Google access token!
**\* NEW RUN @17:50:22 ***
Error: Error
    at Request._callback (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/pokemon-go-node-api/poke.io.js:207:27)
    at self.callback (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.init (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/request/request.js:233:17)
    at new Request (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/request/request.js:129:8)
    at request (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/request/index.js:55:10)
    at /Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/request/index.js:63:12
    at Function.post (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/request/index.js:102:12)
    at compiledProtobuf (/Users/mauricio/AndroidStudioProjects/pokemon-go-node-slack-notifier/node_modules/pokemon-go-node-api/poke.io.js:205:20)

**Comment by BasouKazuma** [comment]
What's your config.json look like? (minus password data)

**Comment by mauscoelho** [comment]
![screen shot 2016-08-18 at 6 56 59 pm](https://cloud.githubusercontent.com/assets/5712300/17792213/f2d77d40-6575-11e6-86ff-e9e6d11c1e67.png)

**Comment by BasouKazuma** [comment]
After `[i] Received Google access token!` it's supposed to say something like `[i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/98/rpc`. That is all a part of the init process from the pokemon-go-node-api. So I'm assuming it's not getting the API Endpoint which results in an error.

Are you using a dummy account (one you don't use to play the game)?
